name: Run InterchainTest

on:
  push: 
    branches:
      - spoorthi/ibctest-optimized

  pull_request:
    branches:
      - main
  
  release:
    types: published
    
  workflow_dispatch:

jobs:
  build_sg_image:
    name: Build docker image
    runs-on: ubuntu-latest

    steps:
      - name: Set up Golang 1.20
        uses: actions/setup-go@v3
        with:
          go-version: ~1.20

      - name: Checkout public-awesome/stargaze
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Stargaze Docker image ✨
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: publicawesome/stargaze:local-dev
          outputs: type=docker,dest=/tmp/sg.tar
      
      - name: Upload the Docker image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: sg
          path: /tmp/sg.tar
        
  # run_defauly:
  #   uses: public-awesome/stargaze/.github/workflows/interchaintest_runner.yml@spoorthi/interchain-test
  #   with:
  #     chain-matrix: 'interchain_test/osmosis.matrix.json'

  # run_icad:
  #   name: icad 🔗
  #   uses: public-awesome/stargaze/.github/workflows/interchaintest_runner.yml@spoorthi/interchain-test
  #   with:
  #     chain-matrix: 'interchain_test/icad.matrix.json'
