name: Run InterchainTest

on:
  push: 
    branches:
      - spoorthi/ibctest-optimized

  pull_request:
    branches:
      - main
  
  release:
    types: published
    
  workflow_dispatch:

jobs:
  build_sg_image:
    name: Build Stargaze image ✨
    runs-on: ubuntu-latest

    steps:
      - name: Set up Golang 1.20
        uses: actions/setup-go@v3
        with:
          go-version: ~1.20

      - name: Checkout public-awesome/stargaze
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Stargaze Docker image ✨
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: publicawesome/stargaze:local-dev
          outputs: type=docker,dest=/tmp/sg.tar
      
      - name: Upload the Docker image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: sg
          path: /tmp/sg.tar
          retention-days: 1

  build_interchaintest:
    name: Build interchaintest 🔗
    runs-on: ubuntu-latest

    steps:
      - name: Set up Golang 1.20
        uses: actions/setup-go@v3
        with:
          go-version: ~1.20

      - name: Checkout strangelove-ventures/interchaintest
        uses: actions/checkout@v3
        with:
          repository: strangelove-ventures/interchaintest

      - name: Build Interchaintest 🔗
        run: make interchaintest

      - name: Upload interchain binary as artifact
        uses: actions/upload-artifact@v3
        with:
            name: interchaintest
            path: ./bin/interchaintest
            retention-days: 1

  run_gaia:
    name: gaia ⚛️
    needs: [build_interchaintest,build_sg_image]
    uses: public-awesome/stargaze/.github/workflows/interchaintest_runner.yml@spoorthi/ibctest-optimized
    with:
      test-matrix: './interchain_test/gaia.matrix.json'

  run_osmosis:
    name: osmosis 🧪
    needs: [build_interchaintest,build_sg_image]
    uses: public-awesome/stargaze/.github/workflows/interchaintest_runner.yml@spoorthi/ibctest-optimized
    with:
      test-matrix: './interchain_test/osmosis.matrix.json'
    
  run_icad:
    name: icad 🔗
    needs: [build_interchaintest,build_sg_image]
    uses: public-awesome/stargaze/.github/workflows/interchaintest_runner.yml@spoorthi/ibctest-optimized
    with:
      test-matrix: './interchain_test/icad.matrix.json'

  cleanup:
    name: Delete artifacts
    needs: [run_gaia,run_osmosis,run_icad]
    runs-on: ubuntu-latest

    steps:
      - name: Delete interchaintest
        uses: geekyeggo/delete-artifact@v2
        with:
          name: interchaintest
          failOnError: false
      
      - name: Delete sg
        uses: geekyeggo/delete-artifact@v2
        with:
          name: sg
          failOnError: false
        