name: lint
on:
  push:
    branches:
      - release/v7.x
  pull_request:
    branches:
      - release/v7.x
jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          args: --timeout 10m --tests=false --skip-dirs="simapp"
          github-token: ${{ secrets.github_token }}
